services:
  - type: web
    name: premium-sphynx-cats
    env: node
    region: frankfurt
    buildCommand: |
      npm install
    startCommand: |
      npm start
    autoDeploy: true
    plan: free
    envVars:
      - key: ADMIN_PASSWORD
        sync: false


